# Created with package:mono_repo v6.6.2
{
  "version": 2,
  "updates": [
    {
      "package-ecosystem": "github-actions",
      "directory": "/",
      "schedule": {
        "interval": "daily"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "my_first_triangle",
      "schedule": {
        "interval": "weekly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "step_01",
      "schedule": {
        "interval": "weekly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "step_02",
      "schedule": {
        "interval": "weekly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "step_03",
      "schedule": {
        "interval": "weekly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "step_04",
      "schedule": {
        "interval": "weekly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "step_05",
      "schedule": {
        "interval": "weekly"
      }
    },
    {
      "package-ecosystem": "pub",
      "directory": "step_06",
      "schedule": {
        "interval": "weekly"
      }
    }
  ]
}
