version: 2
enable-beta-ecosystems: true
updates:
  # Github actions ecosystem.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  # Pub ecosystem.
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/presentation/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/step_01/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/step_02/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/step_03/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/step_04/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/step_05/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/step_06/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/step_07/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/step_08/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/step_09/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/step_10/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/apps/step_11/"
    schedule:
      interval: "daily"
    labels:
      - "autosubmit"
