include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "assets/**"
    - "build/**"
    - "lib/*.g.dart"
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-inference: true

linter:
  rules:
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    package_prefixed_library_names: true
    prefer_const_constructors: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
    test_types_in_equals: true
    throw_in_finally: true
    unawaited_futures: true
    unnecessary_breaks: true
    unnecessary_statements: true
    use_super_parameters: true
