name: Flutter CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: main
          cache: true
      - name: Activate melos
        run: dart pub global activate melos
      - name: Bootstrap
        run: melos bootstrap
      - name: Pub get
        run: melos get
      - name: Enable native assets
        run: flutter config --enable-native-assets
      - name: Analyze
        run: melos analyze --fatal-infos --fatal-warnings
      - name: Format
        run: melos format --set-exit-if-changed
      - name: build
        run: melos run build
      - name: Test
        run: melos test
