name: Flutter CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: main
          cache: true
      - name: dart pub global activate melos
        run: dart pub global activate melos
      - name: melos bootstrap
        run: melos bootstrap
      - name: Analyze
        run: melos analyze --fatal-infos --fatal-warnings
      - name: Flutter pub get
        run: melos get
      - name: Flutter format
        run: melos format --set-exit-if-changed
      - name: Flutter test
        run: melos test
