name: Flutter CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action/config@v3
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Activate melos
        run: dart pub global activate melos
      - name: Bootstrap
        run: melos bootstrap
      - name: Pub get
        run: melos get
      - name: Enable native assets
        run: flutter config --enable-native-assets
      - name: Analyze
        run: melos analyze --fatal-infos --fatal-warnings
      - name: Format
        run: melos format --set-exit-if-changed
      - name: build
        run: melos run build
      - name: Test
        run: melos test
